BEGIN TRANSACTION;
CREATE TABLE "android_metadata" ("locale" TEXT DEFAULT 'en_US');
INSERT INTO `android_metadata` VALUES ('en_US');
CREATE TABLE "Hard" (
	`num`	INTEGER,
	`en`	TEXT,
	`th`	TEXT
);
INSERT INTO `Hard` VALUES(0,'abrupt','ฉับพลัน');
INSERT INTO `Hard` VALUES(1,'banquet','งานเลี้ยง');
INSERT INTO `Hard` VALUES(2,'buckle','หัวเข็มขัด');
INSERT INTO `Hard` VALUES(3,'coherent','ซึ่งสอดคล้อง');
INSERT INTO `Hard` VALUES(4,'courtier','ข้าราชบริพาร');
INSERT INTO `Hard` VALUES(5,'cunning','เจ้าเล่ห์');
INSERT INTO `Hard` VALUES(6,'decoy','นกต่อ');
INSERT INTO `Hard` VALUES(7,'dwell','อาศัย');
INSERT INTO `Hard` VALUES(8,'ebb','น้อยลง');
INSERT INTO `Hard` VALUES(9,'exploit','การกระทำที่กล้าหาญ');
INSERT INTO `Hard` VALUES(10,'fleet','ขบวนเรือ');
INSERT INTO `Hard` VALUES(11,'facade','การหลอกลวง');
INSERT INTO `Hard` VALUES(12,'glee','ความปิติยินดี');
INSERT INTO `Hard` VALUES(13,'glimpse','เหลือบมอง');
INSERT INTO `Hard` VALUES(14,'grumpy','อารมณ์เสีย');
INSERT INTO `Hard` VALUES(15,'gusto','การเพลิดเพลินเต็มที่');
INSERT INTO `Hard` VALUES(16,'hue','สี');
INSERT INTO `Hard` VALUES(17,'implore','อ้อนวอน');
INSERT INTO `Hard` VALUES(18,'inconceivable','ซึ่งเหลือเชื่อ');
INSERT INTO `Hard` VALUES(19,'insight','ความเข้าใจลึกซึ้ง');
INSERT INTO `Hard` VALUES(20,'irrigation','การชลประทาน');
INSERT INTO `Hard` VALUES(21,'issue','ไหลออก');
INSERT INTO `Hard` VALUES(22,'jester','ตัวตลก');
INSERT INTO `Hard` VALUES(23,'keen','กระตือรือร้น');
INSERT INTO `Hard` VALUES(24,'lenient','ปราณี');
INSERT INTO `Hard` VALUES(25,'limber','เตรียมพร้อม');
INSERT INTO `Hard` VALUES(26,'loom','เครื่องทอผ้า');
INSERT INTO `Hard` VALUES(27,'moreover','ยิ่งกว่านั้น');
INSERT INTO `Hard` VALUES(28,'naive','ตรงไปตรงมา');
INSERT INTO `Hard` VALUES(29,'obituary','การประกาศข่าวมรณกรรม');
INSERT INTO `Hard` VALUES(30,'paradigm','แบบอย่าง');
INSERT INTO `Hard` VALUES(31,'placate','ทำให้สงบลง');
INSERT INTO `Hard` VALUES(32,'prosecute','ดำเนินคดี');
INSERT INTO `Hard` VALUES(33,'quoits','กีฬาโยนห่วง');
INSERT INTO `Hard` VALUES(34,'reckon','คิด');
INSERT INTO `Hard` VALUES(35,'rehabilitate','การฟื้นฟูสุขภาพ');
INSERT INTO `Hard` VALUES(36,'ritual','พีธีกรรม');
INSERT INTO `Hard` VALUES(37,'rump','สะโพกสัตว์');
INSERT INTO `Hard` VALUES(38,'significant','มีความหมาย');
INSERT INTO `Hard` VALUES(39,'squabble','ทะเลาะกัน');
INSERT INTO `Hard` VALUES(40,'suave','อ่อนโยน');
INSERT INTO `Hard` VALUES(41,'typify','เป็นตัวอย่าง');
INSERT INTO `Hard` VALUES(42,'urban','เกี่ยวกับเมือง');
INSERT INTO `Hard` VALUES(43,'vague','คลุมเครือ');
INSERT INTO `Hard` VALUES(44,'volatile','ที่เปลี่ยนแปลงได้ง่าย');
INSERT INTO `Hard` VALUES(45,'wade','ผ่านไปอย่างยากลำบาก');
INSERT INTO `Hard` VALUES(46,'woe','ความโศกเศร้า');
INSERT INTO `Hard` VALUES(47,'yap','เห่า');
INSERT INTO `Hard` VALUES(48,'yolk','ไข่แดง');
INSERT INTO `Hard` VALUES(49,'zephyr','ลมอ่อนๆ');
COMMIT;
